### ISSUE TITLE
Don't assume the model is on a CUDA device

### ISSUE THREAD

**Issue by jpsamaroo** [FluxML/DaggerFlux.jl#18]
Currently, `DaggerChain` communicates to Dagger that the wrapped model is located on a CUDA GPU, which is not necessarily true (and shouldn't be a requirement anyway). We should provide functions which can move the model to the GPU and communicate the correct location to Dagger, and/or auto-detect where a model currently resides.

**Comment by DhairyaLGandhi** [comment]
Do we then intend to revert the changes to `daglayer` in #19 before merging?

**Comment by jpsamaroo** [comment]
I believe this has been resolved.
